const keywords = {
  home: [
    "Professional Movers in Nairobi Kenya",
    "Professional moving supplies in Nairobi, Kenya",
    "Professional moving trucks in Kenya",
    "Storage services in Kenya",
    "Warehouse services in Kenya",
    "Professional packing in Kenya",
    "Pic 1: Professional mover packing a moving box",
    "Pic 2: Branded packing boxes",
    "Pic 3: Neatly arranged warehouse",
    "Pic 4: Moving truck being offloaded",
  ],
  about: [
    "Logistics services in Nairobi, Kenya",
    "Clearing and forwarding services in Nairobi, Kenya",
    "Professional local and international relocations in Kenya",
    "Reliable moving services in Nairobi, Kenya",
    "Professional movers in Kenya",
    "Professional movers globally",
  ],
  householdMoving: [
    "Professional household moving services",
    "Professional household relocation services",
    "Long distance moves in Kenya",
    "Local moves in Kenya",
    "Professional packing services in Nairobi, Kenya",
    "Professional international relocation in Nairobi",
    "Professional international moves in Kenya",
    "Safe handling of household possessions",
    "Professional pre-move survey in Nairobi Kenya",
    "Scheduled pre-move assessments in Kenya",
    "Additional services when moving in Kenya",
    "Pic 1: Picture of professional moving surveyor in Nairobi",
    "Estimated moving quotations in Nairobi",
    "Description of moving services",
    "Pic 2: Moving Surveyor with Client in Nairobi Kenya",
    "Competitive moving costs in Nairobi, Kenya",
    "Reliable moving equipment and packing materials in Nairobi, Kenya",
  ],
  office: [
    "Inclusive office relocation services in Kenya",
    "Corporate relocation services",
    "Best office movers in Kenya",
    "Corporate Relocation Companies in Nairobi, Kenya",
    "Pic 1: Picture of professional mover handling a box",
    "Taylor made moving solutions in Kenya",
    "Planning, routing, distribution and logistics of IT and office equipment in Kenya",
    "Specialized computer and office relocations teams in Kenya",
    "Pic 2: Picture of professional movers offloading moving boxes from a moving truck",
    "Professional packers and movers in Nairobi, Kenya",
    "Systematic packing and unpacking of office items in Nairobi",
  ],
  corporate: [
    "Property management specialists in Kenya",
    "Bespoke relocation services in Kenya",
    "Tailored relocation services in Nairobi, Kenya",
    "Corporate staff relocation services in Nairobi",
    "Mobility services in Nairobi",
    "In-country relocation services in East Africa",
    "Professional, experienced and reputable movers in Nairobi, Kenya",
    "Pic 1: Moving truck offloading items at a client’s premises",
  ],
  warehousingAndStorage: [
    "Storage of household or office items in Nairobi",
    "Stock control, order fulfillment, stock replenishment, shipping and delivery of office and household items in Kenya",
    "Efficient document management services in Nairobi, Kenya",
    "Storage and warehousing services in Nairobi, Kenya",
    "Pic 1: Display of neatly arranged warehouse",
    "Pic 2: Display of neatly arranged warehouse",
  ],
  ourBlog: [
    "Most experienced movers in Nairobi, Kenya",
    "Best moving resources on the web",
    "Pic 1: Professional movers dismantling a TV for packing and wrapping",
    "Pic 2: A family enjoying some time together",
    "Moving tips in Kenya",
    "Household moving in Kenya",
    "International moves in Nairobi, Kenya",
    "Office moves in Kenya",
    "Moving with kids in Nairobi, Kenya",
    "Logistics company in Kenya",
    "Storage and warehousing in Kenya",
    "Packing tips in Kenya",
    "Document storage in Nairobi, Kenya",
  ],
}

export default keywords
